language: python
python:
    - "3.6"

# install additonally required packages
addons:
    apt:
        packages:
            - cvs
sudo: true

install:
    - pip install PyYAML
    - pip install codecov
    - pip install schema
    - pip install python-magic
    - pip install pyparsing
    - pip install Sphinx
    - python3 -m pip install BobBuildTool
script:
    - bob --version   
